name: 'Build Pine Icons'
description: 'Build Pine Icon library'

inputs:
  node-version:
    description: 'The version of node to use'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Check out latest
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}

    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}

    - name: Verify NPM Cache
      shell: bash
      run: npm cache verify

    - name: Get NPM cache directory
      id: npm-cache-dir
      shell: bash
      run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

    - name: Cache node_modules
      uses: actions/cache@v4
      id: cache-node-modules
      env:
        cache-name: cache-node-modules
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Set SHA
      uses: nrwl/nx-set-shas@v4

    - name: Install Dependencies
      if: steps.cache-node-modules.ouputs.cache-hit != true
      run: npm ci
      shell: bash

    - name: Build Icons
      run: npx nx run @pine-ds/icons:build
      shell: bash

    - name: Upload Icons Source
      uses: ./.github/workflows/actions/upload-archive
      with:
        name: icons-src${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}
        output: IconsSrc-${{ inputs.node-version }}-${{ hashFiles('**/package-lock.json') }}.zip
        paths: src
