/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PdsIcon {
        /**
          * The color of the icon
         */
        "color"?: string;
        /**
          * Determines if the icon should be flipped when the `dir` is right-to-left (`"rtl"`). This is automatically enabled for icons that are in the `ICONS_TO_FLIP` list and when the `dir` is `"rtl"`. If `flipRtl` is set to `false`, the icon will not be flipped even if the `dir` is `"rtl"`.
         */
        "flipRtl"?: boolean;
        /**
          * This is a combination of both `name` and `src`. If a `src` URL is detected, it will set the `src` property. Otherwise it assumes it's a built-in named SVG and sets the `name` property.
         */
        "icon"?: string;
        /**
          * The name of the icon to use from the built-in set.
         */
        "name"?: string;
        /**
          * The size of the icon. This can be 'small', 'regular', 'medium', 'large', or a custom value (40px, 1rem, etc)
         */
        "size"?: | 'small'   // 12px
    | 'regular'  // 16px
    | 'medium'  // 20px
    | 'large'   // 24px
    | 'auto'
    | string;
        /**
          * Specifies the exact `src` of an SVG file to use.
         */
        "src"?: string;
    }
}
declare global {
    interface HTMLPdsIconElement extends Components.PdsIcon, HTMLStencilElement {
    }
    var HTMLPdsIconElement: {
        prototype: HTMLPdsIconElement;
        new (): HTMLPdsIconElement;
    };
    interface HTMLElementTagNameMap {
        "pds-icon": HTMLPdsIconElement;
    }
}
declare namespace LocalJSX {
    interface PdsIcon {
        /**
          * The color of the icon
         */
        "color"?: string;
        /**
          * Determines if the icon should be flipped when the `dir` is right-to-left (`"rtl"`). This is automatically enabled for icons that are in the `ICONS_TO_FLIP` list and when the `dir` is `"rtl"`. If `flipRtl` is set to `false`, the icon will not be flipped even if the `dir` is `"rtl"`.
         */
        "flipRtl"?: boolean;
        /**
          * This is a combination of both `name` and `src`. If a `src` URL is detected, it will set the `src` property. Otherwise it assumes it's a built-in named SVG and sets the `name` property.
         */
        "icon"?: string;
        /**
          * The name of the icon to use from the built-in set.
         */
        "name"?: string;
        /**
          * The size of the icon. This can be 'small', 'regular', 'medium', 'large', or a custom value (40px, 1rem, etc)
         */
        "size"?: | 'small'   // 12px
    | 'regular'  // 16px
    | 'medium'  // 20px
    | 'large'   // 24px
    | 'auto'
    | string;
        /**
          * Specifies the exact `src` of an SVG file to use.
         */
        "src"?: string;
    }
    interface IntrinsicElements {
        "pds-icon": PdsIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pds-icon": LocalJSX.PdsIcon & JSXBase.HTMLAttributes<HTMLPdsIconElement>;
        }
    }
}
