name: "Pine Nightly Automations"

on:
  schedule:
    - cron: '00 11 * * 2,4' # 11 am UTC Tuesday and Thursday

  workflow_dispatch:
    inputs:
      preid:
        type: choice
        description: Which prerelease id should be used? This is only needed when a version is "prepatch", "preminor", "premajor", or "prerelease".
        options:
          - ''
          - alpha
          - beta
          - rc
          - next

      ref:
        type: string
        description: The branch name, tag, or SHA to be checked out. This can also be left blank.
        default: ''

      tag:
        type: choice
        required: true
        description: Which npm tag should this be published to
        options:
          - latest
          - next
          - dev

      version:
        type: choice
        description: Which version should be published?
        options:
          - ''
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

jobs:
  export-icons:
    uses: ./.github/workflows/release.yml
    with:
      preid: ${{ inputs.preid || '' }}
      ref: ${{ inputs.ref || 'main' }}
      tag: ${{ inputs.tag || 'nightly' }}
      version: ${{inputs.version || '' }}
    secrets: inherit

