name: "Pine Icons Production Release"

on:
  workflow_call:
    inputs:
      preid:
        description: Which prerelease id should be used? This is only needed when a version is "prepatch", "preminor", "premajor", or "prerelease".
        type: string
        default: ''

      ref:
        type: string
        description: The branch name, tag, or SHA to be checked out. This can also be left blank.
        default: ''

      tag:
        type: 'string'
        required: true
        description: Which npm tag should this be published to

      version:
        type: string
        description: Which version should be published?

  workflow_dispatch:
    inputs:
      preid:
        type: choice
        description: Which prerelease id should be used? This is only needed when a version is "prepatch", "preminor", "premajor", or "prerelease".
        options:
          - ''
          - alpha
          - beta
          - rc
          - next

      ref:
        type: string
        description: The branch name, tag, or SHA to be checked out. This can also be left blank.
        default: ''

      tag:
        type: choice
        required: true
        description: Which npm tag should this be published to
        options:
          - latest
          - next
          - dev

      version:
        type: choice
        description: Which version should be published?
        options:
          - ''
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor
          - prerelease

jobs:
  export-icons:
    uses: ./.github/workflows/icon-export.yml
    with:
      preid: ${{ inputs.preid || '' }}
      ref: ${{ inputs.ref || 'next' }}
      tag: ${{ inputs.tag || 'nightly' }}
      version: ${{ inputs.version || '' }}
    secrets: inherit

  publish-icons:
    uses: ./.github/workflows/publish-icons.yml
    needs: export-icons
    if: ${{ needs.export-icons.outputs.nextVersionType != '' }}
    with:
      preid: ${{ inputs.preid}}
      ref: ${{ inputs.ref }}
      tag: ${{ inputs.tag }}
      version: ${{ inputs.version || needs.export-icons.outputs.nextVersionType }}
    secrets: inherit
