name: 'Send Slack Notification'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The SemVer that is being published.'
        required: true

      channel:
        default: 'julian-workflow-test'
        description: 'The channel to send a message to.'

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Pull latest
        run: git pull

      - name: Setup ENV Vars
        run: |
          echo 'PACKAGE_JSON<<EOF' >> $GITHUB_ENV
          cat ./package.json >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$(git log --pretty=format:%s -n 1 HEAD~)" >> $GITHUB_ENV

      - name: Send Slack Notification
        uses: slackapi/slack-github-action@v1.26.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          DATE: ${{ env.CURRENT_DATE }}
          RELEASE_URL: "${{ format('https://github.com/{0}/releases/tag/v{1}', github.repository, fromJSON(env.PACKAGE_JSON).version) }}"
          CHANGELOG_URL: "${{ format('https://pine-icons.netlify.app/changelogs/{0}-changelog.html', env.CURRENT_DATE) }}"
          VERSION: ${{ fromJson(env.PACKAGE_JSON).version }}
          COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
        with:
          channel-id: ${{ inputs.channel }}
          payload-file-path: "./.github/workflows/slack_payloads/release-info.json"

